language: node_js
node_js:
          - 4.2.3
deploy:
  - provider: s3
    access_key_id: AKIAJNDKWK5INDMMD7PQ
    secret_access_key: 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
    bucket: eunoia-labs.staging
    skip_cleanup: true